#define DEFAULT_SERV_PORT 5555
#define DEFAULT_GPS_IP "162.105.31.222"
#define DEFAULT_GPS_PORT 7001
#define QKMJRC ".qkmjrc"
#define THROW_X  12
#define THROW_Y  5
#define INDEX_X  12
#define INDEX_Y  15
#define INDEX_X1 52
#define INDEX_Y1 17
#define INDEX_X2 44 
#define INDEX_Y2 0
#define INDEX_X3 2
#define INDEX_Y3 0 
#define FLOWER_X 20
#define FLOWER_Y 14
#define FLOWER_X1 48
#define FLOWER_Y1 12
#define FLOWER_X2 36
#define FLOWER_Y2 3
#define FLOWER_X3 8
#define FLOWER_Y3 5
#define UP 501
#define DOWN 502
#define LEFT 503
#define RIGHT 504
#define BACKSPACE 127
#define TAB 9
#define SPACE 32
#define ENTER 13
#define CTRL_A 1
#define CTRL_U 21
#define CTRL_D 4
#define CTRL_E 5
#define CTRL_G 7
#define CTRL_H 8
#define CTRL_J 10
#define CTRL_K 11
#define CTRL_L 12
#define CTRL_N 14
#define CTRL_P 16
#define CTRL_S 19
#define HISTORY_SIZE 50
#define org_talk_x 2
#define org_talk_y 23
#define org_comment_x 2
#define org_comment_y 0
#define org_check_x 60
#define org_check_y 13
#define org_eat_x 61
#define org_eat_y 16
#define MAX_PLAYER 30
#define ASK_MODE 1
#define TALK_MODE 2
#define PLAY_MODE 3
#define CHECK_MODE 4
#define EAT_MODE 5
#define GLOBAL_SCREEN_MODE 1
#define PLAYING_SCREEN_MODE 2
#define EAST 1
#define SOUTH 2
#define WEST 3
#define NORTH 4
#define FROM_GPS 1
#define FROM_SERV 2
#define FROM_CLIENT 3
#define WAIT_CARD 0
#define GET_CARD 1
#define THROW_CARD 2
#define EAT 1
#define PONG 2
#define KANG 3
#define MAKE 4
#define TING 5
#define DEFAULT_MONEY 20000
#define DEFAULT_BASE 500
#define DEFAULT_TAI 200
#define PRESS_ANY_KEY_TO_CONTINUE "Çë°´ <ENTER> ¼ÌÐø......"

