version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/minibmy"
      - "/nju09"
      - "/web"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
