/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */
/*

acconfig.h - template used by autoheader to create config.h.in
config.h.in - used by autoconf to create config.h
config.h - created by autoconf; contains defines generated by autoconf

Copyright (c) 1995 Tatu Ylonen <ylo@cs.hut.fi>

*/

/* Define this to the canonical name of your host type (e.g.,
   "sparc-sun-sunos4.0.3"). */
#define HOSTTYPE "i686-pc-linux-gnu"
/* Define if you have SYSV-style /dev/ptmx and /dev/pts/. */
/* #undef HAVE_DEV_PTMX */
/* Define if you have /dev/pts and /dev/ptc devices (as in AIX). */
/* #undef HAVE_DEV_PTS_AND_PTC */
/* Define if you have shadow passwords in /etc/security/passwd (AIX style). */
/* #undef HAVE_ETC_SECURITY_PASSWD */
/* Define if you have shadow passwords in /etc/security/passwd.adjunct
   (SunOS style). */
/* #undef HAVE_ETC_SECURITY_PASSWD_ADJUNCT */
/* Define if you have SIA, Security Integration Architecture (as in
   Tru64 UNIX). */
/* #undef HAVE_SIA */
/* Define if you have shadow passwords in /etc/shadow (Solaris style). */
#define HAVE_ETC_SHADOW 1
/* Define if you have system login defaults in /etc/default/login. */
/* #undef HAVE_ETC_DEFAULT_LOGIN */
/* Define if utmp structure has host field. */
#define HAVE_HOST_IN_UTMP 1
/* Define if utmp structure has addr field. */
#define HAVE_ADDR_IN_UTMP 1
/* Define if utmp structure has id field. */
#define HAVE_ID_IN_UTMP 1
/* Define if utmp structure has name field. */
#define HAVE_NAME_IN_UTMP 1
/* Define if utmp structure has pid field. */
#define HAVE_PID_IN_UTMP 1
/* Define if utmpx structure has syslen field. */
/* #undef HAVE_SYSLEN_IN_UTMPX */
/* Define if /var/adm/lastlog or whatever it is called is a directory
   (e.g. SGI IRIX). */
/* #undef LASTLOG_IS_DIR */
/* Define to use RSAREF. */
/* #undef RSAREF */
/* Define this to be the path of the rsh program to support executing rsh. */
/* #undef RSH_PATH */
/* Define this to be the path of the xauth program. */
/* #undef XAUTH_PATH */
/* Default path for utmp.  Determined by configure. */
/* #undef SSH_UTMP */
/* Default path for wtmp.  Determined by configure. */
/* #undef SSH_WTMP */
/* Default path for lastlog.  Determined by configure. */
/* #undef SSH_LASTLOG */
/* This is defined if we found a lastlog file.  The presence of lastlog.h
   alone is not a sufficient indicator (at least newer BSD systems have
   lastlog but no lastlog.h. */
/* #undef HAVE_LASTLOG */
/* Define this if libutil.a contains BSD 4.4 compatible login(), logout(),
   and logwtmp() calls. */
/* #undef HAVE_LIBUTIL_LOGIN */
/* Location of system mail spool directory. */
/* #undef MAIL_SPOOL_DIRECTORY */
/* Name of user's mail spool file if stored in user's home directory. */
/* #undef MAIL_SPOOL_FILE */
/* Define this to be the default user path if you don't like the default.
   See the --with-path=<path> configure option. */
/* #undef DEFAULT_PATH */
/* Define this if O_NONBLOCK does not work on your system (e.g., Ultrix). */
/* #undef O_NONBLOCK_BROKEN */
/* Define this if sys/syslog.h needs to be included in addition to syslog.h.
   This is the case on some Ultrix versions. */
/* #undef NEED_SYS_SYSLOG_H */
/* Define this to leave out that cipher. */
#define WITH_IDEA 1
/* #undef WITH_DES */
/* #undef WITH_ARCFOUR */
#define WITH_BLOWFISH 1
/* #undef WITH_NONE */
/* Define this to include libwrap (tcp_wrappers) support. */
/* #undef LIBWRAP */
/* #undef HAVE_LIBWRAP */
/* This is defined to pw_encrypt on Linux when using John Faugh's shadow
   password implementation. */
/* #undef crypt */
/* This is defined on 386BSD to preted we are on FreeBSD. */
/* #undef __FreeBSD__ */
/* If defines, this overrides "tty" as the terminal group. */
/* #undef TTY_GROUP */
/* Define this if you want to support Security Dynammics SecurID
   cards. */
/* #undef HAVE_SECURID */
/* Define this if you want to support TIS Authentication scheme. */
/* #undef HAVE_TIS */
/* Define this if you are using HPSUX.  HPUX uses non-standard shared
   memory communication for X, which seems to be enabled by the display name
   matching that of the local host.  This circumvents it by using the IP
   address instead of the host name in DISPLAY. */
/* #undef NONSTANDARD_IP_ADDRESS_X11_KLUDGE */
/* This will enable using magic directory to find x11 sockets */
/* #undef HPSUX_NONSTANDARD_X11_KLUDGE */
/* Define this is compiling on HPSUX 7.x.  This will avoid including
   arpa/inet.h, and will define struct linger in includes.h. */
/* #undef HPSUX7_KLUDGES */
/* Define this if inet_network should be used instead of inet_addr.  This is
   the case on DGUX 5.4. */
/* #undef BROKEN_INET_ADDR */
/* Define this if your system does not like sizeof(struct sockaddr_un) as the
   size argument in bind and connect calls for unix domain sockets. */
/* #undef USE_STRLEN_FOR_AF_UNIX */
/* Define this to use pipes instead of socketpairs for communicating with the
   client program.  Socketpairs do not seem to work on all systems. */
/* #undef USE_PIPES */
/* Directory containing ssh_config, ssh_known_hosts, sshd_pid, etc.  Normally
   /etc. */
/* #undef ETCDIR */
/* Define this if speed_t is defined in stdtypes.h or otherwise gets included
   into ttymodes.c from system headers. */
/* #undef SPEED_T_IN_STDTYPES_H */
/* Define this if compiling on Ultrix.  Defining this does not actually require
   shadow passwords to be present; this just includes support for them. */
/* #undef HAVE_ULTRIX_SHADOW_PASSWORDS */
/* Define this if compiling with SOCKS (the firewall traversal library). */
/* #undef SOCKS */
/* #undef SOCKS4 */
/* #undef SOCKS5 */
/* Define these if on SCO Unix. */
/* #undef HAVE_SCO_ETC_SHADOW */
/* #undef SCO */
/* Additionally define this if on SCO 3.2v5 Unix */
/* #undef SCO5 */
/* Define this if you have getpseudotty() (DYNIX/ptx 2.1) */
/* #undef HAVE_GETPSEUDOTTY */
/* Define this if you have sco-style pty:s (ptyp0, ..., ptyp9, ptyp10...) */
/* #undef HAVE_DEV_PTYP10 */
/* Define this if you have setpgid() (replaces setpgrp) */
#define HAVE_SETPGID 1
/* Define this for HP-UX 10.x shadow passwords */
/* #undef HAVE_HPUX_TCB_AUTH */
/* Support for Secure RPC */
/* #undef SECURE_RPC */
/* Support for Secure NFS */
/* #undef SECURE_NFS */
/* Support for NIS+ */
/* #undef NIS_PLUS */
/* Define this to disable all port forwardings in server (except X11) */
/* #undef SSHD_NO_PORT_FORWARDING */
/* Define this to disable all port forwardings in client (except X11) */
/* #undef SSH_NO_PORT_FORWARDING */
/* Define this to disable X11 forwarding in server */
/* #undef SSHD_NO_X11_FORWARDING */
/* Define this to disable X11 forwarding in client */
/* #undef SSH_NO_X11_FORWARDING */
/* The code in sshconnect.c is written for SOCKS4. If SOCKS5 should be used
   these needs redefining */
/* #undef Rconnect */
/* #undef Rgetsockname */
/* #undef Rgetpeername */
/* #undef Rbind */
/* #undef Raccept */
/* #undef Rlisten */
/* #undef Rselect */
/* #undef Rrecvfrom */
/* #undef Rsendto */
/* #undef Rrecv */
/* #undef Rsend */
/* #undef Rread */
/* #undef Rwrite */
/* #undef Rrresvport */
/* #undef Rshutdown */
/* #undef Rlisten */
/* #undef Rclose */
/* #undef Rdup */
/* #undef Rdup2 */
/* #undef Rfclose */
/* #undef Rgethostbyname */
/* Set this to allow group writeability of $HOME, .ssh and authorized_keys */
/* #undef ALLOW_GROUP_WRITEABILITY */
/* Define if you want the login patches. */
/* #undef USELOGIN */
/* #undef PATH_LOGIN */
/* Define this if your gettimeofday doesn't have TZ parameter */
/* #undef HAVE_NO_TZ_IN_GETTIMEOFDAY */
/* Define this if you want to compile in Kerberos support. */
/* #undef KERBEROS */
/* Define this if you want to compile in Kerberos V5 support.
   KERBEROS must be compiled in as well. This can be done at configure
   time with the --with-kerberos5 argument*/
/* #undef KRB5 */
/* Define this if you want to pass the Kerberos TGT. */
/* #undef KERBEROS_TGT_PASSING */
/* Define this if you dont have SIGINFO as signal but some other macro */
/* #undef HAVE_INCOMPATIBLE_SIGINFO */
/* Define this if your spwd struct defined shadow.h have sp_expire field */
/* #undef HAVE_STRUCT_SPWD_EXPIRE */
/* Define this if your spwd struct defined shadow.h have sp_inact field */
/* #undef HAVE_STRUCT_SPWD_INACT */
/* Define this if you want to enable TCP_NODELAY option */
#define ENABLE_TCP_NODELAY 1
/* File used to override /etc/nologin on a per-user basis.  The default is
   /etc/nologin.allow. */
/* #undef NOLOGIN_ALLOW */
/* Where to find the X11 socket */
/* #undef X11_DIR */
/* Define this if you want to enable SO_LINGER option */
/* #undef ENABLE_SO_LINGER */
/* Define this if you want to enable scp statistics option */
/* #undef WITH_SCP_STATS */
/* Define this to be the path to the passwd program */
/* #undef PASSWD_PATH */
/* Define this if you have SGI proj.h */
/* #undef HAVE_SGI_PROJ_H */
/* Define this if you want to have scp statistics on by default */
/* #undef SCP_STATISTICS_ENABLED */
/* Define this if you want to have scp statistics on by default for each
   file */
/* #undef SCP_ALL_STATISTICS_ENABLED */

/* Define to 1 if you have the `authenticate' function. */
/* #undef HAVE_AUTHENTICATE */

/* Define to 1 if you have the `clock' function. */
#define HAVE_CLOCK 1

/* Define to 1 if you have the `daemon' function. */
#define HAVE_DAEMON 1

/* Define to 1 if you have the <dirent.h> header file, and it defines `DIR'.
   */
#define HAVE_DIRENT_H 1

/* Define to 1 if you have the `fchmod' function. */
#define HAVE_FCHMOD 1

/* Define to 1 if you have the `ftruncate' function. */
#define HAVE_FTRUNCATE 1

/* Define to 1 if you have the `getdtablesize' function. */
#define HAVE_GETDTABLESIZE 1

/* Define to 1 if you have the `gethostname' function. */
#define HAVE_GETHOSTNAME 1

/* Define to 1 if you have the `getpt' function. */
#define HAVE_GETPT 1

/* Define to 1 if you have the `getrusage' function. */
#define HAVE_GETRUSAGE 1

/* Define to 1 if you have the `gettimeofday' function. */
#define HAVE_GETTIMEOFDAY 1

/* Define to 1 if you have the `initgroups' function. */
#define HAVE_INITGROUPS 1

/* Define to 1 if you have the `innetgr' function. */
#define HAVE_INNETGR 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `isastream' function. */
#define HAVE_ISASTREAM 1

/* Define to 1 if you have the <lastlog.h> header file. */
#define HAVE_LASTLOG_H 1

/* Define to 1 if you have the `aud' library (-laud). */
/* #undef HAVE_LIBAUD */

/* Define to 1 if you have the `auth' library (-lauth). */
/* #undef HAVE_LIBAUTH */

/* Define to 1 if you have the `bsd' library (-lbsd). */
#define HAVE_LIBBSD 1

/* Define to 1 if you have the `db' library (-ldb). */
/* #undef HAVE_LIBDB */

/* Define to 1 if you have the `gen' library (-lgen). */
/* #undef HAVE_LIBGEN */

/* Define to 1 if you have the `inet' library (-linet). */
/* #undef HAVE_LIBINET */

/* Define to 1 if you have the `m' library (-lm). */
/* #undef HAVE_LIBM */

/* Define to 1 if you have the `nsl' library (-lnsl). */
#define HAVE_LIBNSL 1

/* Define to 1 if you have the `s' library (-ls). */
/* #undef HAVE_LIBS */

/* Define to 1 if you have the `sec' library (-lsec). */
/* #undef HAVE_LIBSEC */

/* Define to 1 if you have the `security' library (-lsecurity). */
/* #undef HAVE_LIBSECURITY */

/* Define to 1 if you have the `seq' library (-lseq). */
/* #undef HAVE_LIBSEQ */

/* Define to 1 if you have the `shadow' library (-lshadow). */
/* #undef HAVE_LIBSHADOW */

/* Define to 1 if you have the `socket' library (-lsocket). */
/* #undef HAVE_LIBSOCKET */

/* Define to 1 if you have the `sun' library (-lsun). */
/* #undef HAVE_LIBSUN */

/* Define to 1 if you have the <login_cap.h> header file. */
/* #undef HAVE_LOGIN_CAP_H */

/* Define to 1 if you have the <machine/endian.h> header file. */
/* #undef HAVE_MACHINE_ENDIAN_H */

/* Define to 1 if you have the `makeutx' function. */
/* #undef HAVE_MAKEUTX */

/* Define to 1 if you have the `memcpy' function. */
#define HAVE_MEMCPY 1

/* Define to 1 if you have the `memmove' function. */
#define HAVE_MEMMOVE 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <ndir.h> header file, and it defines `DIR'. */
/* #undef HAVE_NDIR_H */

/* Define to 1 if you have the <netinet/in_system.h> header file. */
/* #undef HAVE_NETINET_IN_SYSTEM_H */

/* Define to 1 if you have the <netinet/in_systm.h> header file. */
#define HAVE_NETINET_IN_SYSTM_H 1

/* Define to 1 if you have the <netinet/ip.h> header file. */
#define HAVE_NETINET_IP_H 1

/* Define to 1 if you have the <netinet/tcp.h> header file. */
#define HAVE_NETINET_TCP_H 1

/* Define to 1 if you have the `openpty' function. */
/* #undef HAVE_OPENPTY */

/* Define to 1 if you have the <paths.h> header file. */
#define HAVE_PATHS_H 1

/* Define to 1 if you have the `putenv' function. */
#define HAVE_PUTENV 1

/* Define to 1 if you have the `pw_encrypt' function. */
/* #undef HAVE_PW_ENCRYPT */

/* Define to 1 if you have the `random' function. */
#define HAVE_RANDOM 1

/* Define to 1 if you have the `remove' function. */
#define HAVE_REMOVE 1

/* Define to 1 if you have the `revoke' function. */
/* #undef HAVE_REVOKE */

/* Define to 1 if you have the <rusage.h> header file. */
/* #undef HAVE_RUSAGE_H */

/* Define to 1 if you have the `setlogin' function. */
/* #undef HAVE_SETLOGIN */

/* Define to 1 if you have the `setluid' function. */
/* #undef HAVE_SETLUID */

/* Define to 1 if you have the `setpgid' function. */
#define HAVE_SETPGID 1

/* Define to 1 if you have the `setpgrp' function. */
#define HAVE_SETPGRP 1

/* Define to 1 if you have the `setsid' function. */
#define HAVE_SETSID 1

/* Define to 1 if you have the <sgtty.h> header file. */
#define HAVE_SGTTY_H 1

/* Define to 1 if you have the <shadow.h> header file. */
#define HAVE_SHADOW_H 1

/* Define to 1 if you have the `snprintf' function. */
#define HAVE_SNPRINTF 1

/* Define to 1 if you have the `socketpair' function. */
#define HAVE_SOCKETPAIR 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `strchr' function. */
#define HAVE_STRCHR 1

/* Define to 1 if you have the `strerror' function. */
#define HAVE_STRERROR 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if `st_blksize' is member of `struct stat'. */
#define HAVE_STRUCT_STAT_ST_BLKSIZE 1

/* Define to 1 if your `struct stat' has `st_blksize'. Deprecated, use
   `HAVE_STRUCT_STAT_ST_BLKSIZE' instead. */
#define HAVE_ST_BLKSIZE 1

/* Define to 1 if you have the <sys/conf.h> header file. */
/* #undef HAVE_SYS_CONF_H */

/* Define to 1 if you have the <sys/dir.h> header file, and it defines `DIR'.
   */
/* #undef HAVE_SYS_DIR_H */

/* Define to 1 if you have the <sys/ioctl.h> header file. */
#define HAVE_SYS_IOCTL_H 1

/* Define to 1 if you have the <sys/ndir.h> header file, and it defines `DIR'.
   */
/* #undef HAVE_SYS_NDIR_H */

/* Define to 1 if you have the <sys/resource.h> header file. */
#define HAVE_SYS_RESOURCE_H 1

/* Define to 1 if you have the <sys/select.h> header file. */
#define HAVE_SYS_SELECT_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/stream.h> header file. */
/* #undef HAVE_SYS_STREAM_H */

/* Define to 1 if you have the <sys/time.h> header file. */
#define HAVE_SYS_TIME_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have <sys/wait.h> that is POSIX.1 compatible. */
#define HAVE_SYS_WAIT_H 1

/* Define to 1 if you have the <termios.h> header file. */
#define HAVE_TERMIOS_H 1

/* Define to 1 if you have the `times' function. */
#define HAVE_TIMES 1

/* Define to 1 if you have the `ttyslot' function. */
#define HAVE_TTYSLOT 1

/* Define to 1 if you have the `ulimit' function. */
#define HAVE_ULIMIT 1

/* Define to 1 if you have the <ulimit.h> header file. */
#define HAVE_ULIMIT_H 1

/* Define to 1 if you have the `umask' function. */
#define HAVE_UMASK 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the <usersec.h> header file. */
/* #undef HAVE_USERSEC_H */

/* Define to 1 if you have the <utime.h> header file. */
#define HAVE_UTIME_H 1

/* Define to 1 if you have the <utmpx.h> header file. */
#define HAVE_UTMPX_H 1

/* Define to 1 if you have the <utmp.h> header file. */
#define HAVE_UTMP_H 1

/* Define to 1 if you have the `vhangup' function. */
#define HAVE_VHANGUP 1

/* Define to 1 if you have the `waitpid' function. */
#define HAVE_WAITPID 1

/* */
#define HAVE_ZLIB 1

/* Define to 1 if you have the `_getpty' function. */
/* #undef HAVE__GETPTY */

/* Define to 1 if `major', `minor', and `makedev' are declared in <mkdev.h>.
   */
/* #undef MAJOR_IN_MKDEV */

/* Define to 1 if `major', `minor', and `makedev' are declared in
   <sysmacros.h>. */
/* #undef MAJOR_IN_SYSMACROS */

/* Name of package */
#define PACKAGE "sshbbs"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* Define as the return type of signal handlers (`int' or `void'). */
#define RETSIGTYPE void

/* Define to use RSAREF. */
/* #undef RSAREF */

/* The size of a `int', as computed by sizeof. */
#define SIZEOF_INT 4

/* The size of a `long', as computed by sizeof. */
#define SIZEOF_LONG 4

/* The size of a `short', as computed by sizeof. */
#define SIZEOF_SHORT 2

/* Define to 1 if the `S_IS*' macros in <sys/stat.h> do not work properly. */
/* #undef STAT_MACROS_BROKEN */

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to 1 if you can safely include both <sys/time.h> and <time.h>. */
#define TIME_WITH_SYS_TIME 1

/* Version number of package */
#define VERSION "1.0"

/* Define to 1 if your processor stores words with the most significant byte
   first (like Motorola and SPARC, unlike Intel and VAX). */
/* #undef WORDS_BIGENDIAN */

/* Define if you need to in order for stat and other things to work. */
/* #undef _POSIX_SOURCE */

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define to `int' if <sys/types.h> doesn't define. */
/* #undef gid_t */

/* Define as `__inline' if that's what the C compiler calls it, or to nothing
   if it is not supported. */
/* #undef inline */

/* Define to `int' if <sys/types.h> does not define. */
/* #undef mode_t */

/* Define to `long' if <sys/types.h> does not define. */
/* #undef off_t */

/* Define to `unsigned' if <sys/types.h> does not define. */
/* #undef size_t */

/* Define to `int' if <sys/types.h> doesn't define. */
/* #undef uid_t */
