#include "bbs.h"
/* bbs.c */
void do_delay(int i);
int underline_post(int ent, struct fileheader *fileinfo, char *direct);
int allcanre_post(int ent, struct fileheader *fileinfo, char *direct);
int set_safe_record(void);
void setqtitle(char *stitle);
int chk_currBM(struct boardheader *bh, int isbig);
void setquotefile(char filepath[]);
char *setuserfile(char *buf, char *filename);
char *setbpath(char *buf, char *boardname);
char *setbfile(char *buf, char *boardname, char *filename);
int deny_me(char *bname);
void shownotepad(void);
void make_blist(void);
void make_blist_full(void);
int junkboard(void);
void Select(void);
int postfile(char *filename, char *nboard, char *posttitle, int mode);
int get_a_boardname(char *bname, char *prompt);
int do_cross(int ent, struct fileheader *fileinfo, char *direct);
int cmpfilename(struct fileheader *fhdr);
int topfile_post(int ent, struct fileheader *fhdr, char *direct);
int super_select_board(char *bname);
int digest_post(int ent, struct fileheader *fhdr, char *direct);
int do_reply(struct fileheader *fh);
int transferattach(char *buf, int size, FILE *fp, FILE *fpto);
void do_quote(char *filepath, int quote_mode);
int do_post(void);
void add_loginfo(char *filepath);
void add_crossinfo(char *filepath, int mode);
int show_board_notes(char bname[30]);
int stringfilter(char *title, int mode);
int edit_post(int ent, struct fileheader *fileinfo, char *direct);
int edit_title(int ent, struct fileheader *fileinfo, char *direct);
int mark_post(int ent, struct fileheader *fileinfo, char *direct);
int has_perm_commend(char *userid);
int mark_commend(int ent, struct fileheader *fileinfo, char *direct);
int markdel_post(int ent, struct fileheader *fileinfo, char *direct);
int mark_minus_del_post(int ent, struct fileheader *fileinfo, char *direct);
int del_range(int ent, struct fileheader *fileinfo, char *direct);
int del_post(int ent, struct fileheader *fileinfo, char *direct);
int Save_post(int ent, struct fileheader *fileinfo, char *direct);
int Import_post(int ent, struct fileheader *fileinfo, char *direct);
int check_notespasswd(void);
int what_to_do(void);
int into_announce(void);
int forward_post(int ent, struct fileheader *fileinfo, char *direct);
int forward_u_post(int ent, struct fileheader *fileinfo, char *direct);
int Goodbye(void);
int Info(void);
int Conditions(void);
int Welcome(void);
int cmpbnames(struct boardheader *brec, char *bname);
void setbdir(char *buf, char *boardname, int Digestmode);
int zmodem_sendfile(int ent, struct fileheader *fileinfo, char *direct);
int deleted_mode(void);
int junk_mode(void);
int marked_mode(void);
int thread_mode(void);
void Add_Combine(char *board, struct fileheader *fileinfo);
int commend_article(char *board, struct fileheader *fileinfo);
int is_in_commend(char *board, struct fileheader *fileinfo);
int del_commend(int offset);
int do_commend(char *board, struct fileheader *fileinfo);
int count_commend(void);
int show_commend(void);
/* record.c */
long get_num_records(char *filename, int size);
long get_num_records_excludeBottom(char *filename, int size);
int apply_record(char *filename, int (*fptr)(void *), int size);
int get_record(char *filename, void *rptr, int size, int id);
int get_records(char *filename, void *rptr, int size, int id, int number);
int substitute_record(char *filename, void *rptr, int size, int id);
int insert_record(char *fpath, void *data, int size, int pos, int num);
int delete_range(char *filename, int id1, int id2);
int update_file(char *dirname, int size, int ent, int (*filecheck)(void *), void (*fileupdate)(void *));
/* delete.c */
int d_board(void);
void offline(void);
int online(void);
void getuinfo(FILE *fn);
int d_user(char *cid);
int kick_user(struct user_info *userinfo, int mode);
/* main.c */
int ifinprison(char *name);
int cmpuids(char *uid, struct userec *up);
int dosearchuser(char *userid);
void do_abort_bbs(void);
void abort_bbs(void);
void set_numofsig(void);
int main(int argc, char **argv);
int egetch(void);
void update_endline(void);
void showtitle(char *title, char *mid);
void docmdtitle(char *title, char *prompt);
void relogin(void);
int Q_Goodbye(void);
/* stuff.c */
int dashf(const char *fname);
int dashd(char *fname);
int dashl(char *fname);
int pressanykey(void);
int pressreturn(void);
int askyn(char str[80], int defa, int gobottom);
void printdash(char *mesg);
void bell(void);
void touchnew(void);
void strtolower(char *dst, char *src);
int deltree(char *dst);
int do_exec(char *com, char *wd);
char *horoscope(int month, int day);
/* mail.c */
char *email_domain(void);
void filter(char *line);
int chkmail(void);
int check_query_mail(char qry_mail_dir[80]);
int mailall(void);
void m_internet(void);
void m_init(void);
int m_send(char userid[]);
int M_send(void);
int m_new(void);
int mail_reply(int ent, struct fileheader *fileinfo, char *direct);
int mail_forward(int ent, struct fileheader *fileinfo, char *direct);
int mail_u_forward(int ent, struct fileheader *fileinfo, char *direct);
int m_read(void);
int invalidaddr(char *addr);
int g_send(void);
int mail_file(char tmpfile[80], char userid[80], char title[80]);
int mail_buf(char *buf, char userid[], char title[]);
int ov_send(void);
int voter_send(char *fname);
int club_send(void);
int doforward(char *filepath, char *oldtitle, int mode);
int m_cancel(char userid[]);
int post_reply(int ent, struct fileheader *fileinfo, char *direct);
int mailtoall(int mode, int hour);
/* register.c */
int release_email(char *userid, char *email);
int id_with_num(char userid[12 + 1]);
void new_register(void);
int invalid_email(char *addr);
void check_register_info(void);
/* xyz.c */
void loaduserkeys(void);
int modify_user_mode(int mode);
int x_csh(void);
int showperminfo(unsigned int pbits, int i, int use_define);
int x_copykeys(void);
int x_setkeys(void);
int x_setkeys2(void);
int x_setkeys3(void);
int x_setkeys4(void);
int x_setkeys5(void);
unsigned int setperms(unsigned int pbits, char *prompt, int numbers, int (*showfunc)(unsigned int, int, int), int param);
int x_level(void);
int x_userdefine(void);
int x_cloak(void);
void x_edits(void);
void a_edits(void);
void a_edits2(void);
void x_lockscreen(void);
int heavyload(float maxload);
int sendgoodwish(char *uid);
void x_dict(void);
void x_tt(void);
void x_worker(void);
void x_tetris(void);
void x_winmine(void);
void x_winmine2(void);
void x_recite(void);
void x_ncce(void);
void x_chess(void);
void x_qkmj(void);
void x_quickcalc(void);
void x_freeip(void);
void x_showuser(void);
int ent_bnet(char *cmd);
int x_denylevel(void);
int s_checkid(void);
char *directfile(char *fpath, char *direct, char *filename);
int zsend_file(char *from, char *title);
void inn_reload(void);
/* talk.c */
void creat_list(void);
int t_pager(void);
int t_query(char q_id[12 + 2]);
int show_special(char *id2);
void num_alcounter(void);
int num_useshell(void);
int num_active_users(void);
int t_cmpuids(int uid, struct user_info *up);
int t_talk(void);
int ttt_talk(struct user_info *userinfo);
int servicepage(int line, char *mesg);
int talkreply(void);
void endmsg(void);
int seek_in_file(char filename[80], char seekstr[80]);
int listfilecontent(char *fname);
int addtofile(char filename[80], char str[256]);
int addtooverride(char *uident);
int del_from_file(char filename[80], char str[80]);
int deleteoverride(char *uident, char *filename);
int override_add(void);
void t_friend(void);
void t_reject(void);
struct user_info *t_search(char *sid, int pid, int invisible_check);
int getfriendstr(void);
int getrejectstr(void);
int wait_friend(void);
/* read.c */
struct keeploc *getkeep(char *s, int def_topline, int def_cursline);
void fixkeep(char *s, int first, int last);
void i_read(int cmdmode, char *direct, int (*dotitle)(void), char *(*doentry)(int, void *, char *), const struct one_key *rcmdlist, int ssize);
int auth_search_down(int ent, struct fileheader *fileinfo, char *direct);
int auth_search_up(int ent, struct fileheader *fileinfo, char *direct);
int post_search_down(int ent, struct fileheader *fileinfo, char *direct);
int post_search_up(int ent, struct fileheader *fileinfo, char *direct);
int show_author(int ent, struct fileheader *fileinfo, char *direct);
int friend_author(int ent, struct fileheader *fileinfo, char *direct);
int SR_BMfunc(int ent, struct fileheader *fileinfo, char *direct);
int SR_first_new(int ent, struct fileheader *fileinfo, char *direct);
int SR_last(int ent, struct fileheader *fileinfo, char *direct);
int SR_first(int ent, struct fileheader *fileinfo, char *direct);
int SR_read(int ent, struct fileheader *fileinfo, char *direct);
int SR_author(int ent, struct fileheader *fileinfo, char *direct);
int t_search_down(int ent, struct fileheader *fileinfo, char *direct);
int t_search_up(int ent, struct fileheader *fileinfo, char *direct);
int thread_up(int ent, struct fileheader *fileinfo, char *direct);
int thread_down(int ent, struct fileheader *fileinfo, char *direct);
int sread(int passonly, int readfirst, int pnum, int auser, struct fileheader *ptitle);
int searchpattern(char *filename, char *query);
/* comm_lists.c */
char *sysconf_str(char *key);
int sysconf_eval(char *key);
void load_sysconf(void);
int domenu(char *menu_name);
/* namecomplete.c */
void CreateNameList(void);
void AddNameList(char *name);
void ApplyToNameList(int ((*fptr)(void)));
int chkstr(char *otag, char *tag, char *name);
int namecomplete(char *prompt, char *data);
int usercomplete(char *prompt, char *data);
/* chat.c */
void printchatline(const char *str);
void chat_clear(void);
void print_chatid(char *chatid);
int ent_chat(char *chatbuf);
void setpager(void);
/* maintain.c */
int select_mail(char *userid, char *email, char *record);
int check_systempasswd(void);
int setsystempasswd(void);
void deliverreport(char *title, char *str);
void securityreport(char *str, char *content);
int get_grp(char seekstr[80]);
void stand_title(char *title);
int m_info(void);
int m_newbrd(void);
int m_editbrd(void);
int m_mclean(void);
int m_trace(void);
int f_cp(char *src, char *dst, int mode);
int m_register(void);
int m_ordainBM(void);
int do_ordainBM(const char *userid, const char *abname);
int m_retireBM(void);
int do_retireBM(const char *userid, const char *abname);
int retireBM(char *uid, char *bname);
int retire_allBM(char *uid);
int m_addpersonal(void);
/* edit.c */
int write_header(FILE *fp, int mode);
void addsignature(FILE *fp, int blank);
void keep_fail_post(void);
int vedit(char *filename, int saveheader, int modifyheader);
/* more.c */
int NNread_init(void);
void setcalltime(void);
int countln(char *fname);
void printacbar(void);
void check_calltime(void);
void R_monitor(void);
int ansimore(char *filename, int promptend);
int ansimore_withzmodem(char *filename, int promptend, char *title);
int ansimore2(char *filename, int promptend, int row, int numlines);
int ansimorestuff(char *filename, int promptend);
int ansimore2stuff(char *filename, int promptend, int row, int numlines);
/* help.c */
void show_help(char *fname);
int mainreadhelp(void);
int mailreadhelp(void);
int selbacknumberhelp(void);
int backnumberhelp(void);
/* bcache.c */
void attach_err(int shmkey, char *name);
void *attach_shm(int shmkey, int shmsize);
void reload_boards(void);
void resolve_boards(void);
int apply_boards(int (*func)(struct boardmem *));
struct boardmem *getbcache(char *bname);
int updatelastpost(char *board);
int hasreadperm(struct boardheader *bh);
int getbnum(char *bname);
int canberead(char *bname);
int noadm4political(char *bname);
int haspostperm(char *bname);
int posttest(char *uid, char *bname);
int hideboard(char *bname);
int normal_board(char *bname);
int innd_board(char *bname);
int is1984_board(char *bname);
int political_board(char *bname);
int club_board(char *bname);
int clubsync(char *boardname);
void resolve_ucache(void);
void setuserid(int num, char *userid);
int searchnewuser(void);
void getuserid(char *userid, unsigned int uid);
int searchuser(char *userid);
int getuser(char *userid);
char *u_namearray(char buf[][12 + 1], int *pnum, char *tag);
void resolve_utmp(void);
int getnewutmpent(struct user_info *up);
int apply_ulist(int (*fptr)(struct user_info *));
int search_ulist(struct user_info *uentp, int (*fptr)(int, struct user_info *), int farg);
int search_ulistn(struct user_info *uentp, int (*fptr)(int, struct user_info *), int farg, int unum);
int count_logins(struct user_info *uentp, int (*fptr)(int, struct user_info *), int farg, int show);
int t_search_ulist(int (*fptr)(int, struct user_info *), int farg);
int user_isonline(char *userid);
void update_ulist(struct user_info *uentp, int uent);
void update_utmp(void);
int get_utmp(void);
void update_utmp2(void);
int who_callme(struct user_info *uentp, int (*fptr)(int, struct user_info *), int farg, int me);
int insertuseridhash(struct useridhashitem *ptr, int size, char *userid, int num);
int getbmnum(char *userid);
struct user_info *query_uindex(int uid, int dotest);
int count_uindex(int uid);
int count_uindex_telnet(int uid);
char *get_temp_sessionid(char *temp_sessionid);
void show_small_bm(char *board);
int setbmstatus(int online);
/* boards.c */
void GoodBrds(void);
void EGroup(char *cmd);
void Boards(void);
void New(void);
int unread_position(char *dirfile, struct boardmem *bptr);
void update_postboards(void);
void brc_update(void);
int brc_initial(char *boardname, int keep);
void clear_new_flag_quick(int t);
void clear_all_new_flag(void);
int Read(void);
int showhell(void);
int showprison(void);
int clubtest(char *board);
/* smth_screen.c */
void setfcolor(int i, int j);
void setbcolor(int i);
void resetcolor(void);
int num_noans_chr(char *str);
void clear(void);
void initscr(void);
void refresh(void);
void redoscr(void);
void move(int y, int x);
void getyx(int *y, int *x);
void clear_whole_line(int i);
void clrtoeol(void);
void clrtobot(void);
void outc(unsigned char c);
void outns(const char *str, int n);
void outs(const char *str);
void prints(char *format, ...);
void scroll(void);
void rscroll(void);
void noscroll(void);
void saveline(int line, int mode, char *buffer);
void do_naws(int ln, int col);
void show_message(char msg[]);
/* io.c */
void oflush(void);
void init_alarm(void);
void add_io(int fd, int timeout);
void add_flush(void (*flushfunc)(void));
int num_in_buf(void);
int igetkey(void);
int ask(char *prompt);
int getdata(int line, int col, char *prompt, char *buf, int len, int echo, int clearlabel);
int raw_write(int fd, char *buf, int len);
int raw_read(int fd, char *buf, int len);
int multi_getdata(int line, int col, int maxcol, char *prompt, char *buf, int len, int maxline, int clearlabel);
/* term.c */
void init_tty(void);
void term_init(void);
void do_move(int destcol, int destline, int (*outc)(void));
/* userinfo.c */
void register_fail(char *userid);
char *str_to_upper(char *str);
int write_pop_user(char *user, char *userid, char *pop_name);
void permtostr(int perm, char *str);
void disply_userinfo(struct userec *u, int real);
int uinfo_query(struct userec *u, int real, int unum);
void x_info(void);
void x_fillform(void);
/* vote.c */
void makevdir(char *bname);
void setvfile(char *buf, char *bname, char *filename);
int b_closepolls(void);
int vote_maintain(char *bname);
int b_vote_maintain(void);
int m_voter(void);
int b_vote(void);
int b_results(void);
void m_vote(void);
void x_vote(void);
int x_results(void);
/* announce.c */
int valid_fname(char *str);
int countstr(char *s0, char *s1);
void a_prompt(int bot, char *pmt, char *buf, int len);
int a_Save(char *path, char *key, struct fileheader *fileinfo, int nomsg);
int check_import(char *anboard);
int an_log(char *action, char *path);
int a_Import(char *direct, struct fileheader *fileinfo, int nomsg);
int a_menusearch(char *path, char *key, int level);
void a_menu(char *maintitle, char *path, int lastlevel, int lastbmonly);
void linkto(char *path, char *fname, char *title);
int add_grp(char group[80], char gname[80], char bname[80], char title[80]);
int del_grp(char grp[80], char bname[80], char title[80]);
int edit_grp(char bname[80], char grp[80], char title[80], char newtitle[100]);
void Announce(void);
void Personal(char *cmd);
int chk_currBM_Personal(char *BMstr);
int logvisit(time_t timein, const char *path);
int getvisit(int n[2], const char *path);
int add_anpath(char *title, char *path);
int select_anpath(void);
int save_anpath(char titles[20][80], char paths[20][1024]);
int read_anpath(char titles[20][80], char paths[20][1024]);
/* sendmsg.c */
int canmsg(struct user_info *uin);
int canmsg_offline(char *uid);
int s_msg(void);
int do_sendmsg(char *uid, struct user_info *uentp, char msgstr[256], int mode, int userpid);
int wall(void);
int wall_telnet(void);
int friend_wall(void);
void r_msg2(void);
void r_msg(void);
void block_msg(void);
void unblock_msg(void);
int friend_login_wall(struct user_info *pageinfo);
int show_allmsgs(void);
/* bm.c */
int deny_user(void);
int addclubmember(char *uident, int clubnum);
int clubmember(void);
int deny_from_article(int ent, struct fileheader *fileinfo, char *direct);
int mail_buf_slow(char *userid, char *title, char *content, char *sender);
/* list.c */
int myfriend(unsigned uid);
int hisfriend(struct user_info *uentp);
int isreject(struct user_info *uentp);
int allusers(void);
void setlistrange(int i);
void Users(void);
int t_friends(void);
int t_users(void);
int choose(int update, int defaultn, void (*title_show)(void), int (*key_deal)(int, int, int), int (*list_show)(void), int (*read)(int, int));
/* goodbye.c */
int countlogouts(char filename[80]);
void user_display(char *filename, int number, int mode);
void showstuff(char buf[256]);
/* bbsgopher.c */
int interrupt_chk(void);
void clear_gophertmpfile(void);
int readfield(int fd, char *ptr, int maxlen);
int readline(int fd, char *ptr, int maxlen);
int savetmpfile(char tmpname[]);
void print_gophertitle(void);
void printgopher_title(void);
void g_refresh(void);
int deal_gopherkey(int ch, int allnum, int pagenum);
void enterdir(char path[]);
int get_con(char *servername, int port);
int do_gopher(int page, int num);
int show_gopher(void);
void showout(void);
int gopher(char serv[], char dire[], int port, char title[]);
/* fileshm.c */
int fill_shmfile(int mode, char *fname, int shmkey);
void show_goodbyeshm(void);
void show_welcomeshm(void);
int show_endline(void);
/* postheader.c */
int post_header(struct postheader *header);
/* convcode.c */
void switch_code(void);
void conv_init(void);
char *gb2big(char *s, int *plen, int inst);
char *big2gb(char *s, int *plen, int inst);
/* five.c */
void five_pk(int fd, int first);
/* tmachine.c */
/* addressbook.c */
int addressbook(void);
/* backnumber.c */
void setbacknumberfile(char *path, char *filename);
int readbacknumber(int ent, struct bknheader *bkninfo, char *direct);
int new_backnumber(void);
int selectbacknumber(void);
int do_intobacknumber(char *filename, time_t t);
/* common.c */
int cmpIP(char *left, char *right);
/* sec_hand.c */
int sec_hand(void);
/* regular.c */
int checkf(char *str);
/* 1984.c */
void set1984file(char *path, char *filename);
void post_1984_to_board(char *dir, struct fileheader *fileinfo);
void post_to_1984(char *file, struct fileheader *fileinfo, int mode);
void do1984menu(void);
/* moneycenter.c */
int moneycenter(void);
void *loadData(char *filepath, void *buffer, size_t filesize);
void saveData(void *buffer, size_t filesize);
int show_welcome(char *filepath, int startline, int endline);
char *get_simple_date_str(time_t *tt);
char *get_date_str(time_t *tt);
/* editboard.c */
int editboard(char *bname);
/* power_select.c */
int full_search_action(char *whattosearch);
int power_action(char *filename, int id1, int id2, char *select, int action);
char *strstr2(char *s, char *s2);
int power_select(int ent, struct fileheader *fileinfo, char *direct);
/* tmpl.c */
int m_template(void);
int choose_tmpl(void);
/* logger.c */
void logbuf(char *buf, char *title, int headerindex);
