name: BMYBBS Frontend

on:
  push:
    paths:
      - ".github/workflows/node.yml"
      - "web/**"
      - "content-parser"
    branches:
      - master
  pull_request:
    paths:
      - ".github/workflows/node.yml"
      - "web/**"
      - "content-parser"
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6.0.3
        with:
          version: 10

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "22.x"
          cache: "pnpm"

      - name: Install deps
        run: pnpm install

      - name: Build front-end
        working-directory: web
        run: npm run build
