name: BMYBBS Frontend

on:
  push:
    paths:
      - '.github/workflows/node.yml'
      - 'web/**'
      - 'content-parser'
    branches:
      - master
  pull_request:
    paths:
      - '.github/workflows/node.yml'
      - 'web/**'
      - 'content-parser'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install deps
        run: yarn --frozen-lockfile

      - name: Build front-end
        working-directory: web
        run: npm run build

