name: BMYBBS Frontend

on:
  push:
    paths:
      - '.github/workflows/node.yml'
      - 'web/**'
      - 'content-parser'
    branches:
      - master
  pull_request:
    paths:
      - '.github/workflows/node.yml'
      - 'web/**'
      - 'content-parser'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install

      - name: Build front-end
        working-directory: web
        run: npm run build

